services:
  weather-api:
    build: ./weather/
    ports:
      - 4000:3001
    volumes:
      - /var/log/weather-api/:/log/server-logs/
    environment:
      - OWM_API_KEY

  weather-client:
    build: ./client/
    ports:
      - 5000:80
    links:
      - weather-api
    environment:
      - WEATHER_API_URL=http://localhost:4000
